# Initial Workflow: No Data Quality Controls

Login to Control-M and Explore the Domains
==
1. In the [button label="Control-M"](tab-0) tab, log in using the following credentials:
	- Username: `emuser`
	- Password: `password`
2. Explore the different Control-M Domains
	- **Planning**: Where you design, edit, and organize workflows (Folders, Jobs, and Sub-Folders). You’ll use this domain to open deployed workflows and verify workflow business logic.
	![Nov-14-2025_at_16.12.29-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/4f2a8622a98c1c605fb64673628696a8/assets/Nov-14-2025_at_16.12.29-image.png)
	- **Monitoring**: Where you observe and control live workflows as they execute. Displays job statuses, dependencies, SLAs, and overall service health.
	![Nov-14-2025_at_16.13.50-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/ebe258b143e135da227f4a422626a748/assets/Nov-14-2025_at_16.13.50-image.png)
	- **Managed File Transfer** (MFT): Manages and tracks file movement across systems. Offers visibility into file transfer progress, retries, and failures.
	![Nov-14-2025_at_16.14.10-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/f0cd8d8394946d3fad9b42f96faee5b3/assets/Nov-14-2025_at_16.14.10-image.png)
	- **Tools**: Provides access to administrative utilities like site standards, calendars, and variables.
	![Nov-14-2025_at_16.15.39-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/fc4fc18bd18b8ff48199cd019e3f3143/assets/Nov-14-2025_at_16.15.39-image.png)
	- **Alerts**: Displays notifications and actionable messages when a problem or exception has occurred while processing a job or folder.
	![Nov-14-2025_at_16.15.59-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/611cc6fff55f01f1174c6d5821cc8e57/assets/Nov-14-2025_at_16.15.59-image.png)
	- **Application Menu** (top-right corner): The navigation hub for all Control-M Applications. Allows you to switch to between the current view and Configuration.
	![Nov-14-2025_at_16.17.17-image.png](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/db06cd2521af02341b38976b3c6a20bd/assets/Nov-14-2025_at_16.17.17-image.png)

Open the Social Media Data Feeds Workflow
==
1. In the [button label="Control-M"](tab-0) tab, select the **Planning** domain from the top navigation bar.
2. Open the **Folders and Jobs** tab.
3.  Select the folder: `zzz-social-media-feeds`
4.  Click **Open Workspace** .
5.  Click **Modify** to exit Read-Only Mode and allow changes to the workspace.

>[!NOTE]
>**Workflow Explanation:**
>
>The workflow begins with **zzz-get-feeds**, which retrieves raw social-media data from an API and writes it to feeds.csv.
>
>Once the file is created, event triggers launch **zzz-ai-score**, a Python-based job that uploads the CSV to Gemini, generates sentiment scores for each record, and writes the results to sentiment_scores.csv.
>
>The final job, **zzz-ai-score-cat**, reads that file, classifies each record as “Approved” or “Declined” based on its numeric sentiment score, and outputs two categorized CSVs.
>
>The pipeline will process the entire dataset end-to-end with no validation, filtering, or gating steps between ingestion and AI scoring. The workflow runs, but it runs blind—with no guardrail to stop low quality data before it hits expensive AI scoring.

Run the Social Media Data Feeds Workflow
==
1. Click <img src="https://play.instruqt.com/assets/tracks/arqnvuii8xfc/f3959ad50a5d344f71c4e33f4220c350/assets/Oct-02-2025_at_13.36.56-image.png" alt="app-icon" style="display:inline; height:50px; vertical-align:middle;" />  in the top toolbar, then select **Run Workspace** to submit the workflow for execution.
2. In the confirmation pop-up, click **Run**.
3.  Navigate to the **Monitoring** domain.
4. Click **All Active Jobs** and **Open**.
5. Review the output of job execution.
![run-flow.gif](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/0fa01c29d768d468c8addd1ddca2f345/assets/run-flow.gif)

(Optional) View Output Files
===
1. In the [button label="Code Editor"](tab-1 ) tab, review the output files generated by the workflow.

	- `feeds.csv`: This file is created by **zzz-get-feeds**,  and contains the raw social-media posts pulled from the API—no filtering, no validation, just the full dataset exactly as retrieved.
	- `sentiment_scores.csv`: This file is generated by **zzz-ai-score**, and includes all original fields from feeds.csv plus a new column, Sentiment Score, assigned by the Gemini model. Every row from the feed is scored.
	- `approved.csv`: This file is generated by **zzz-ai-score-cat**, and contains only the rows where the sentiment score is 0.75 or higher, labeled as “Approved.”
	- `declined.csv`: This file is genreated by **zzz-ai-score-cat**, and contains all remaining rows—anything with a sentiment score below 0.75, labeled as “Declined.”

>[!NOTE]
>You will see the full dataset containing Likes ≥ 50, and Shares ≥ 10.

Summary
==
![initial-workflow-da.gif](https://play.instruqt.com/assets/tracks/t2hkmzw8ofv4/c1b3ba7b14b1b219dbaa7d94ef53d575/assets/initial-workflow-da.gif)
