apiVersion: v1
kind: Service
metadata:
  name: ${CTM_USER_CODE}-sts-0-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30002
  selector:
    statefulset.kubernetes.io/pod-name: ${CTM_USER_CODE}-sts-0
