##############################################################################
# Spark Github Actions Workflow
#
# This workflow will perform a find replace on all files in a folder
##############################################################################
name: replace-substring-in-folder
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    inputs:
      folder:
        description: Folder to update
        required: true
        type: string
      find-str:
        description: Find string
        required: true
        type: string
      replace-str:
        description: Replace string
        required: true
        type: string

permissions: 
  contents: write
  
jobs:
  ReplaceSubstring:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Replace substrings in folder
        run: |
          cd "${{ inputs.folder }}"
          ls -l
          echo "Updating json files..."
          echo "Replacing ${{ inputs.find-str }} with ${{ inputs.replace-str }}"
          for file in $(find . -type f -name "*"); do
            sed -i -E 's|${{ inputs.find-str }}|${{ inputs.replace-str }}|g' $file
          done
          cat local_repo/cp_jenkins.json

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Committing substring replacement in ${{ inputs.folder }}
